@startuml
actor User
entity Local_storage

User -> System: Selects task to delete
System -> User: Prompts confirmation dialog
System -> Local_storage: Deletes task
Local_storage --> System: Acknowledgment
System -> User: Displays success message


@enduml
